name: spdx_license_fetcher
description: Fetches license file by its SPDX identifier and print it to the terminal as text.
version: 0.1.0-alpha
repository: https://github.com/arsharaj/spdx-license-fetcher
issue_tracker: https://github.com/arsharaj/spdx-license-fetcher/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  xml: ^5.1.0

dev_dependencies:
  pedantic: ^1.9.0
