name: spdx_license_fetcher
description: Console based dart application fetches license file by its SPDX identifier and print it to the terminal as markdown.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  xml: ^5.1.0

dev_dependencies:
  pedantic: ^1.9.0
